---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: ubuntu-15.04
    driver_config:
      box: opscode-ubuntu-15.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-15.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[my_hostname::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
